version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: pinny_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinny
    volumes:
      - pinny_db_data:/var/lib/postgresql/data

volumes:
  pinny_db_data: